dist: bionic

language: generic

services:
- docker

env:
  global:
  - DEPLOY_CONDITION=v1.18.0 # Don't forget to update here to latest kube minor version
  matrix:
  - KUBE_VERSION=v1.18.0
  - KUBE_VERSION=v1.17.0
  - KUBE_VERSION=v1.16.4

before_script:
# https://github.com/rootless-containers/usernetes/blob/master/.travis.yml
# Install Docker 18.09+ for enabling DOCKER_BUILDKIT
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- sudo cat /etc/docker/daemon.json
- sudo rm -f /etc/docker/daemon.json
- sudo systemctl restart docker

script:
- make docker-image

after_success:
# Download and install kubectl
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download and install kind
- curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
# Create a new kubernetes cluster
- kind create cluster --image="kindest/node:${KUBE_VERSION}"
# Show version and cluster-info
- kubectl version && kubectl cluster-info
# Run update-storage-objects
- docker run -v ${HOME}/.kube:${HOME}/.kube -e SKIP_UPDATE_OBJECT_ERROR=1 --network host zlabjp/update-storage-objects:latest

deploy:
  provider: script
  script: echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin && DOCKER_TAG="${TRAVIS_TAG}" scripts/docker-push.sh
  on:
    branch: master
    tags: true
    condition: "$KUBE_VERSION =~ ^$DEPLOY_CONDITION"
