language: go

go:
- "1.12.x"

services:
- docker

env:
  global:
  - DEPLOY_CONDITION=v1.14.2 # Don't forget to update here to latest kube minor version
  matrix:
  - KUBE_VERSION=v1.14.2 NODE_TAG=v1.14.2@sha256:33539d830a6cf20e3e0a75d0c46a4e94730d78c7375435e6b49833d81448c319
  - KUBE_VERSION=v1.13.6 NODE_TAG=v1.13.6@sha256:9e07014fb48c746deb98ec8aafd58c3918622eca6063e643c6e6d86c86e170b4

script:
- make docker-image

after_success:
# Download and install kubectl
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download and install kind
- curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.3.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
# Create a new kubernetes cluster
- kind create cluster --image="kindest/node:${NODE_TAG}"
# Set KUBECONFIG environment variable
- export KUBECONFIG="$(kind get kubeconfig-path)"
# Show version and cluster-info
- kubectl version && kubectl cluster-info
# Run update-storage-objects
- docker run -v ${HOME}/.kube:${HOME}/.kube -e KUBECONFIG --network host zlabjp/update-storage-objects:latest

deploy:
  provider: script
  script: echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin && DOCKER_TAG="${TRAVIS_TAG}" scripts/docker-push.sh
  on:
    branch: master
    tags: true
    condition: "$KUBE_VERSION =~ ^$DEPLOY_CONDITION"
