[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/component-base"
  branch = "release-1.15"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v11.1.0"

[prune]
  go-tests = true
  unused-packages = true
