[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

# vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use json.Number(expiresIn) (type json.Number) as type string in field value
# vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
# vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:249:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v11.1.0"

[prune]
  go-tests = true
  unused-packages = true
