platform: linux
image_resource:
  type: docker-image
  source:
    repository: k8s.gcr.io/debian-base-amd64
    tag: "0.3"
inputs:
- name: version
outputs:
- name: output
run:
  path: sh
  args:
  - -exuc
  - |
    apt-get -yy update
    apt-get -yy install jq
    jq -n '{
      "KUBE_VERSION": $version
    }' --arg version "$(cat version/version)" > output/build-args-file
