apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-objects-updater
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: update-storage-objects
subjects:
- kind: ServiceAccount
  name: storage-objects-updater
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-storage-objects
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: storage-objects-updater
      containers:
      - name: update-storage-objects
        image: zlabjp/update-storage-objects:1.8
      restartPolicy: Never
